touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
touch index.html | wget http://localhost:9000 -O q
